# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7b5da78a-c305-4b1a-97a6-ff99a7a74f1c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7b5da78a-c305-4b1a-97a6-ff99a7a74f1c".device = "/dev/disk/by-uuid/7b5da78a-c305-4b1a-97a6-ff99a7a74f1c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B4D9-3AE6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-c149f000-1b2b-43d2-ab9b-67cfbb106a0b"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
